/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AliossPicker: typeof import('./../components/alioss-picker.vue')['default']
    FAlert: typeof import('./../components/f-alert.vue')['default']
    Favicon: typeof import('./../components/favicon.vue')['default']
    GenericActions: typeof import('./../components/generic-actions.vue')['default']
    InlineTest: typeof import('./../components/InlineTest.vue')['default']
    KevyMask: typeof import('./../components/kevy-mask.vue')['default']
    ModelformFui: typeof import('./../components/Modelform/Fui.vue')['default']
    ModelformFuiWidget: typeof import('./../components/Modelform/FuiWidget.vue')['default']
    ModelformUni: typeof import('./../components/Modelform/Uni.vue')['default']
    ModelformUniBatchButton: typeof import('./../components/Modelform/UniBatchButton.vue')['default']
    ModelformUniMiniButton: typeof import('./../components/Modelform/UniMiniButton.vue')['default']
    ModelformUniTableField: typeof import('./../components/Modelform/UniTableField.vue')['default']
    ModelformUniWidget: typeof import('./../components/Modelform/UniWidget.vue')['default']
    PageLayout: typeof import('./../components/page-layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreRadar: typeof import('./../components/ScoreRadar.vue')['default']
    ThreadBody: typeof import('./../components/thread-body.vue')['default']
    ThreadHead: typeof import('./../components/thread-head.vue')['default']
    ThreadList: typeof import('./../components/thread-list.vue')['default']
    TinymceText: typeof import('./../components/tinymce-text.vue')['default']
    UploadFile: typeof import('./../components/upload-file.vue')['default']
    UploadImage: typeof import('./../components/upload-image.vue')['default']
    WxAvatar: typeof import('./../components/wx-avatar.vue')['default']
    WxLogin: typeof import('./../components/WxLogin.vue')['default']
    XAlbum: typeof import('./../components/x-album.vue')['default']
    XAlert: typeof import('./../components/x-alert.vue')['default']
    XBottom: typeof import('./../components/x-bottom.vue')['default']
    XButton: typeof import('./../components/x-button.vue')['default']
    XChatbar: typeof import('./../components/x-chatbar.vue')['default']
    XCheckbox: typeof import('./../components/x-checkbox.vue')['default']
    XCheckboxPoll: typeof import('./../components/x-checkbox-poll.vue')['default']
    XNavigator: typeof import('./../components/x-navigator.vue')['default']
    XPicker: typeof import('./../components/x-picker.vue')['default']
    XRadio: typeof import('./../components/x-radio.vue')['default']
    XRadioPoll: typeof import('./../components/x-radio-poll.vue')['default']
    XSubtitle: typeof import('./../components/x-subtitle.vue')['default']
    XTagbutton: typeof import('./../components/x-tagbutton.vue')['default']
    XText: typeof import('./../components/x-text.vue')['default']
    XTitle: typeof import('./../components/x-title.vue')['default']
  }
}
