// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Favicon: typeof import('./../components/favicon.vue')['default']
    InlineTest: typeof import('./../components/InlineTest.vue')['default']
    ModelFormUni: typeof import('./../components/ModelForm/Uni.vue')['default']
    ModelFormUniBatchButton: typeof import('./../components/ModelForm/UniBatchButton.vue')['default']
    ModelFormUniMiniButton: typeof import('./../components/ModelForm/UniMiniButton.vue')['default']
    ModelFormUniTableField: typeof import('./../components/ModelForm/UniTableField.vue')['default']
    ModelFormUniWidget: typeof import('./../components/ModelForm/UniWidget.vue')['default']
    PageLayout: typeof import('./../components/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreRadar: typeof import('./../components/ScoreRadar.vue')['default']
    WxLogin: typeof import('./../components/WxLogin.vue')['default']
  }
}
