// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AliossPicker: typeof import('./../components/alioss-picker.vue')['default']
    copy: typeof import('./../components/x-alert copy.vue')['default']
    Favicon: typeof import('./../components/favicon.vue')['default']
    InlineTest: typeof import('./../components/InlineTest.vue')['default']
    ModelformUni: typeof import('./../components/Modelform/Uni.vue')['default']
    ModelformUniBatchButton: typeof import('./../components/Modelform/UniBatchButton.vue')['default']
    ModelformUniMiniButton: typeof import('./../components/Modelform/UniMiniButton.vue')['default']
    ModelformUniTableField: typeof import('./../components/Modelform/UniTableField.vue')['default']
    ModelformUniWidget: typeof import('./../components/Modelform/UniWidget.vue')['default']
    PageLayout: typeof import('./../components/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreRadar: typeof import('./../components/ScoreRadar.vue')['default']
    ThreadBody: typeof import('./../components/thread-body.vue')['default']
    ThreadHead: typeof import('./../components/thread-head.vue')['default']
    ThreadList: typeof import('./../components/thread-list.vue')['default']
    UploadFile: typeof import('./../components/upload-file.vue')['default']
    UploadImage: typeof import('./../components/upload-image.vue')['default']
    WxAvatar: typeof import('./../components/wx-avatar.vue')['default']
    WxLogin: typeof import('./../components/WxLogin.vue')['default']
    XAlbum: typeof import('./../components/x-album.vue')['default']
    XAlert: typeof import('./../components/x-alert.vue')['default']
    XButton: typeof import('./../components/x-button.vue')['default']
    XPicker: typeof import('./../components/x-picker.vue')['default']
  }
}
