describe("validator api:", function()
  local validator = require("xodel.validator")
  it("test year_month", function()
    local check = validator.year_month
    assert.are.equal("2010.01", check('2010.01'))
    assert.has_error(function()
      local res, err = check('2010.31')
      error(err)
    end, "格式不正确，正确举例：2010.01")
  end)
end)
